services:
  auth-postgres:
      image: postgres:17
      container_name: auth-postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=chat_app_admin
        - POSTGRES_PASSWORD=chat_app_admin
        - POSTGRES_DB=chat_app_db
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - auth-network
      ports:
        - "5432:5432"

  auth-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  auth-redis:
      image: redis/redis-stack:7.4.0-v8
      container_name: auth-redis
      restart: unless-stopped
      volumes:
        - redis_data:/data
      networks:
        - auth-network
      ports:
        - "6379:6379"
        - "8001:8001"

volumes:
  pgdata:
  redis_data:

networks:
  auth-network: